version: '3.8'

services:
  nginx_hubsearch:
    image: nginx:latest
    ports:
      - 12345:80
    depends_on:
      - php_hubsearch
    volumes:
      - ./app:/srv/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  redis_hubsearch:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  php_hubsearch:
    build: docker/php
    depends_on:
      - redis_hubsearch
    env_file:
      - app/.env.local
    volumes:
      - ./app:/srv/www
#      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini


volumes:
  redis_data:
    driver: local
