services:
  nginx_hubsearch:
    image: nginx:latest
    ports:
      - 12345:80
    volumes:
      - ./app:/srv/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php_hubsearch:
    build: docker/php
    volumes:
      - ./app:/srv/www
