<?php  //[STAMP] 81376fd38e23d8998457ef0ff74d0f61
// phpcs:ignoreFile
namespace App\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait AppTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
