v1_controllers:
    resource:
        path: ../src/Score/Controller/
        namespace: App\Controller
    type: attribute
    prefix: '/v1'

score:
    path: /score
    controller: App\Score\ScoreController::index
